
if(PLATFORM_WASM)
    set(QT6_DIR_CMAKE_PREFIX_PATH $ENV{QT_DIR_WASM}/${CMAKE_BUILD_TYPE}/lib/cmake)
    set(CMAKE_TOOLCHAIN_FILE Qt${QT_INSTALL_PREFIX}/lib/cmake/Qt6/qt.toolchain.cmake)
    set(CMAKE_EXECUTABLE_SUFFIX .js)
else()
    set(QT6_DIR_CMAKE_PREFIX_PATH $ENV{QT_DIR_NEW}/${CMAKE_BUILD_TYPE})
endif()

set(CMAKE_PREFIX_PATH ${QT6_DIR_CMAKE_PREFIX_PATH})

message(STATUS "Qt Environment : " ${QT6_DIR_CMAKE_PREFIX_PATH})

find_package(QT NAMES Qt6 COMPONENTS Core Gui Widgets REQUIRED)
find_package(Qt${QT_VERSION_MAJOR} COMPONENTS Core Gui Widgets Charts REQUIRED)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

get_target_property(QMAKE_EXECUTABLE Qt${QT_VERSION_MAJOR}::qmake IMPORTED_LOCATION)
get_filename_component(QT_BIN_DIR ${QMAKE_EXECUTABLE} DIRECTORY)

find_program(WINDEPLOYQT_EXECUTABLE windeployqt HINTS ${QT_BIN_DIR})
set(PLATFORM_DEPLOYQT_EXECUTABLE ${WINDEPLOYQT_EXECUTABLE})
